import { Translation, Language } from './types';

export const TRANSLATIONS: Record<Language, Translation> = {
    en: {
        dropText: "Drop your videos here to lighten",
        browse: "Browse Files",
        files: "File Queue",
        queued: "Queued",
        processing: "Processing...",
        completed: "Done",
        settings: "Basic Settings",
        advanced: "Advanced Settings",
        format: "Output Format",
        resolution: "Resolution",
        audio: "Audio Control",
        removeAudio: "Remove Audio (Mute)",
        fileMgmt: "File Management",
        moveToTrash: "Move original to trash after compression",
        start: "Start Compression",
        stop: "Stop",
        totalProgress: "Total Progress",
        eta: "ETA",
        remove: "Remove",
        clearAll: "Clear All",
        theme: "Theme",
        language: "Language",
        custom: "Custom",
        lockRatio: "Lock Ratio",
        quality: "Compression Quality",
        highQuality: "Quality",
        highCompression: "Compress",
        instagram: "Instagram (1080p)",
        youtube: "YouTube (4K)",
        originalSizeText: "Original Size",
        estResultText: "Est. Result",
        estReductionText: "Est. Batch Reduction",
        reductionOff: "OFF",
        batchNote: "Advanced SVT-AV1 scaling applied to {count} files",
        outputDest: "Saving Location",
        sameAsOriginal: "Same as original folder",
        selectFolder: "Select destination folder",
        saveTo: "Save to",
        legal: "Terms & Privacy",
        activateTitle: "Activate VideoLighter",
        activateSub: "Enter your license key to unlock powerful video compression.",
        licenseKey: "License Key",
        activateBtn: "Activate License",
        verifying: "Verifying your license...",
        buyNow: "Don't have a key? Buy one now",
        support: "Support",
        invalidKey: "Invalid or expired license key.",
        machineLocked: "This key is already registered to another device.",
        activationSuccess: "Activation successful! Welcome to VideoLighter.",
        turbo: "Turbo Acceleration Mode",
        turboTip: "Enables hardware acceleration and optimized SVT-AV1 presets for up to 3x faster compression.",
        parallel: "Parallel Processing",
        parallelTip: "Compress multiple videos at once. Higher numbers use more CPU.",

        // Preset Descriptions
        bestQuality: "Best Quality",
        bestQualityDesc: "Visually identical to original. ~30-50% reduction.",
        balanced: "Balanced",
        balancedDesc: "Great for sharing. High quality, optimized size.",
        smallestSize: "Smallest Size",
        smallestSizeDesc: "Maximum compression for quick messaging.",

        // Magic Features
        subjectiveVQ: "Perceptual Quality Magic",
        subjectiveVQTip: "Focuses quality where human eyes notice most (faces, brightness). Reduces size while looking better!",
        hdr: "Keep HDR Colors (10-bit)",
        hdrTip: "Preserves the vivid colors of iPhone/Galaxy HDR videos. Essential for modern phone clips.",
        metadata: "Metadata Cleaning",
        metadataTip: "Removes technical metadata (GPS, device info) to protect your privacy.",

        highEfficiency: "Next-Gen Compression (AV1)",
        highEfficiencyTip: "Enables ~30% better compression using latest AV1 technology. Requires AV1 codec on playback device.",
        downloadCodec: "Download AV1 Codec",
        folderOpen: "Open in folder",
    },
    ko: {
        dropText: "동영상을 이곳에 드래그하여 용량을 줄이세요",
        browse: "파일 찾기",
        files: "파일 대기열",
        queued: "대기 중",
        processing: "처리 중...",
        completed: "완료",
        settings: "기본 설정",
        advanced: "고급 설정",
        format: "출력 형식",
        resolution: "해상도 조절",
        audio: "오디오 설정",
        removeAudio: "오디오 제거 (음소거)",
        fileMgmt: "파일 관리",
        moveToTrash: "압축 완료 후 원본 휴지통으로 이동",
        start: "압축 시작",
        stop: "중단",
        totalProgress: "전체 진행률",
        eta: "남은 시간",
        remove: "삭제",
        clearAll: "전체 삭제",
        theme: "테마",
        language: "언어",
        custom: "직접 입력",
        lockRatio: "비율 고정",
        quality: "압축률 설정",
        highQuality: "고화질",
        highCompression: "고압축",
        instagram: "인스타그램 (1080p)",
        youtube: "유튜브 (4K)",
        originalSizeText: "원본 용량",
        estResultText: "예상 결과",
        estReductionText: "평균 압축 효율",
        reductionOff: "감소",
        batchNote: "SVT-AV1 엔진이 {count}개의 파일을 최적화 중입니다",
        outputDest: "파일 저장 위치",
        sameAsOriginal: "원본 파일과 같은 폴더에 저장",
        selectFolder: "저장 위치 직접 선택",
        saveTo: "저장 경로",
        legal: "이용약관 및 개인정보 정책",
        activateTitle: "VideoLighter 활성화",
        activateSub: "라이선스 키를 입력하여 강력한 동영상 압축 기능을 잠금 해제하세요.",
        licenseKey: "라이선스 키 입력",
        activateBtn: "라이선스 활성화",
        verifying: "라이선스를 확인 중입니다...",
        buyNow: "라이선스 활성화 키가 없으신가요? 지금 구매하기",
        support: "고객 지원",
        invalidKey: "유효하지 않거나 만료된 키입니다.",
        machineLocked: "이 키는 이미 다른 기기에 등록되어 있습니다.",
        activationSuccess: "활성화 성공! VideoLighter의 모든 기능을 사용하실 수 있습니다.",
        turbo: "터보 가속 모드",
        turboTip: "하드웨어 가속(GPU) 및 최적화된 프리셋을 사용하여 압축 속도를 최대 3배 이상 높줍니다.",
        parallel: "병렬 압축",
        parallelTip: "여러 파일을 동시에 압축합니다. CPU 성능에 따라 속도가 달라집니다.",

        // Preset Descriptions
        bestQuality: "최고 화질",
        bestQualityDesc: "원본과 거의 동일한 화질. 용량은 30-50% 줄어듭니다.",
        balanced: "균형 모드 (추천)",
        balancedDesc: "공유하기 딱 좋은 품질과 용량입니다. 가장 안전한 선택!",
        smallestSize: "용량 우선",
        smallestSizeDesc: "카톡 전송용으로 최고! 용량을 극한까지 줄입니다.",

        // Magic Features
        subjectiveVQ: "인지 화질 최적화 (매직)",
        subjectiveVQTip: "기계적인 계산 대신, 사람 눈이 민감한 곳(얼굴 등) 위주로 화질을 챙깁니다. 용량은 더 줄고 화질은 더 좋아 보입니다!",
        hdr: "HDR 색감 유지 (10-bit)",
        hdrTip: "전문가급 영상 배포를 위한 고대역폭 색상을 지원합니다.",
        metadata: "메타데이터 클리닝",
        metadataTip: "GPS, 기기 정보 등 사생활과 직결된 기술 정보를 깨끗이 제거합니다.",

        folderOpen: "저장 폴더 열기",
        highEfficiency: "차세대 고압축 (AV1)",
        highEfficiencyTip: "최신 AV1 기술로 30% 더 압축합니다. 재생 기기에 AV1 코덱이 필요할 수 있습니다.",
        downloadCodec: "AV1 코덱 다운로드 (무료)",
    }
};

export const FORMAT_OPTIONS = ['MP4', 'WebM', 'MKV', 'GIF'] as const;
export const RESOLUTION_OPTIONS = ['Original', '4K', '1080p', '720p', '480p', 'Instagram', 'YouTube', 'Custom'] as const;
